### ISSUE TITLE
changelog-draft fails on reference to issue in another repo

### ISSUE THREAD

**Issue by vakila** [mapbox/github-release-tools#29]
If a commit message includes a string of the form `#12345`, this is interpreted by `changelog-draft` as a reference to an issue in the given repo. 

This breaks when a user includes such a string referencing an issue in a different repo, e.g. if a commit to `mapbox-gl-js` includes a string like  `[Fixes #1234](https://github.com/mapbox/mapbox-gl-native/issues/1234)`. See [this commit](https://github.com/mapbox/mapbox-gl-js/pull/8309/commits/059e375afad6702f14a5e5a421fd5ad5a1c398d6) for an example.

- [ ] add error handling so that if an octokit issue request 404s we proceed with other issue requests, and (or at least) a useful error message is displayed
- [ ] update the regex that `changelog-draft` is using to identify issue references to account for this edge case. 

cc @ahk

**Comment by ahk** [comment]
Closing this because we're updating the `changelog-draft` workflow to work on PRs instead of commits and also to not rely on automated issue references.

**Comment by ahk** [comment]
Closing this because we're updating the changelog-draft workflow to work on PRs instead of commits and also to not rely on automated issue references.
