### ISSUE TITLE
PRs with empty bodies throw exception

### ISSUE THREAD

**Issue by yunikkk** [mapbox/github-release-tools#45]
https://github.com/mapbox/github-release-tools/blob/main/src/parse-and-categorize-changelog-entries.js#L30 will fail with exception
`TypeError: Cannot read property ‘match’ of null
    at parseEntriesFromPullRequests`
 if body of the PR is empty (eg https://github.com/mapbox/mapbox-maps-android/pull/954).

Probably empty body should be treated as NOT containing changelog entry.

**Comment by kiryldz** [comment]
Noting I did edit https://github.com/mapbox/mapbox-maps-android/pull/954 to have a non-empty body to have a better look at https://github.com/mapbox/mapbox-maps-android-internal/issues/865 in future.
